Rewrite using no external programs except for git

diff --git a/git-some b/git-some
--- a/git-some
+++ b/git-some
@@ -15,49 +15,56 @@ commit_count=${1-1}
 
 # Limit to 100 files (file-00.txt to file-99.txt).
 commit_limit=100
-max_index=$(($commit_limit - 1))
-placeholder_length=${#max_index}
+max_index=$((commit_limit - 1))
 
-if grep --quiet --invert-match '^[[:digit:]]*$' <<< $commit_count; then
-  >&2 echo Need a positive number for number of commits to generate, got: $commit_count
+if ! [[ "$commit_count" =~ ^[0-9]+$ ]]; then
+  >&2 printf 'Need a positive number for number of commits to generate, got: %s\n' \
+    "$commit_count"
+
   exit 1
 fi
 
-search_pattern=
-for ((i = 1; i <= $placeholder_length; i++)); do
-  search_pattern=$search_pattern?;
-done
-search_pattern=file-$search_pattern.txt
+placeholder_length=${#max_index}
+printf -v search_pattern '%*s' "$placeholder_length" ''
+search_pattern="file-${search_pattern// /?}.txt"
 
-file_count=$(find . -maxdepth 1 -name "$search_pattern" | wc -l)
-if [[ $(($file_count + $commit_count)) -gt $commit_limit ]]; then
-  >&2 echo Cannot create $commit_count file\(s\). $commit_limit file\(s\) are permitted and $file_count file\(s\) have already been created. $(($commit_limit - $file_count)) file\(s\) left.
+shopt -s nullglob
+# shellcheck disable=SC2206
+files=($search_pattern)
+file_count=${#files[@]}
+if ((file_count + commit_count >= max_index)); then
+  >&2 printf 'Cannot create %s file(s). %s file(s) are permitted and %s file(s) have already been created. %s file(s) left.\n' \
+             "$commit_count" \
+             "$commit_limit" \
+             "$file_count" \
+             "$((commit_limit - file_count))"
+
   exit 3
 fi
 
-for ((commit = 1; commit <= $commit_count; commit++)); do
-  # Try to find an untaken file between 0 and ($commit_limit -1).
+for ((commit = 1; commit <= commit_count; commit++)); do
+  # Try to find an untaken file between 0 and ($commit_limit - 1).
   while true; do
-    up_to_limit=$(($RANDOM % $commit_limit))
-    filename=$(printf "file-%0${placeholder_length}d.txt" $up_to_limit)
+    number=$((RANDOM % commit_limit))
+    printf -v filename "file-%0*d.txt" "$placeholder_length" "$number"
 
     [[ -f "$filename" ]] || break
   done
 
   # Create file.
-  echo contents for $filename > "$filename"
+  printf 'contents for %s\n' "$filename" > "$filename"
 
   # Stage file.
   if ! git add -- "$filename"; then
-    rm -f "$filename"
+    rm -f -- "$filename"
     exit 2
   fi
 
-  # Commit
+  # Create commit.
   if ! git commit --message "commit message for $filename"; then
-    git rm --force "$filename" > /dev/null
+    git rm --force -- "$filename" > /dev/null
     exit 4
   fi
 
-  echo
+  printf '\n'
 done
